- name: Install Wordpress Application
  hosts: web001

- name: Wait for web001 to be completed
  hosts: web002
  become: yes
  become_method: sudo
  become_user: root
  tasks: 
    - name: Wait unitil web001 is ready
      wait_for:
        path: /tmp/web001
      delegate_to: ansible.rhlab.ch
      remote_user: azureadm

    - name: Install libsemanage-python
      yum: 
        name: libsemanage-python
        state: installed

- name: Install Wordpress Application
  hosts: web002
  become: true
  vars:
    httpd_scripting: 'php'

    wordpress_database_host: "{{ hostvars['web001'].ansible_local.custom.rhlabip.prvip }}"
    wordpress_database: wordpress_db
    wordpress_user: wordpress_usr
    wordpress_password: ywIapecJalg6
    wordpress_plugins:
      - name: wp-super-cache
        version: 1.4.5
      #- name: jetpack
      #  version: 3.7.2
      - name: lipsum
    #wordpress_themes:
      #- name: xcel
      #  version: 1.0.9
  roles:
    - bertvv.httpd
    - ansible-role-wordpress

  tasks:

    - name: Rsync Wordpress contents
      command: rsync -avP /usr/share/wordpress/ /var/www/html/

    - name: create upload Directory
      file: 
        state: directory
        path: /var/www/html/wp-content/uploads
        mode: 0775

    - name: Change Pemission
      file: 
        owner: apache
        group: apache
        path: /var/www/html
        recurse: yes

    - name: Restart WebServer
      service:
        name: httpd
        state: restarted

    - debug: 
        msg: | 
          WordPress successfuly installed 
          Connect with following URL: http://{{ web002_pubip }}/wp-admin  

