- name: Wait for all hosts to complete
  hosts: web001
  become: yes
  become_method: sudo
  become_user: root
  tasks: 
    - name: Wait unitil web002 is ready
      wait_for:
        path: /tmp/web002
      delegate_to: ansible.rhlab.ch
      remote_user: azureadm

- name: Install MariaDB 
  hosts: web001
  become: yes
  become_method: sudo
  become_user: root
  vars:
    wp_version: 4.0
    wp_install_dir: '/var/sites/awesome_wordpress_site'
    wp_db_name: 'wpdb'
    wp_db_user: 'admin'
    wp_db_password: 'redhat1234'
    wp_db_host: 'localhost'
  roles:
    - bertvv.mariadb
