- name: Wait for web001 to be completed
  hosts: web002
  become: yes
  become_method: sudo
  become_user: root
  tasks: 
    - name: Wait unitil web001 is ready
      wait_for:
        path: /tmp/web001
      delegate_to: ansible.rhlab.ch
      remote_user: azureadm

- name: Install Wordpress Application
  hosts: web002
  become: yes
  become_method: sudo
  become_user: root
  vars:
    wp_version: 4.0
    wp_install_dir: '/var/sites/awesome_wordpress_site'
    wp_db_name: 'wpdb'
    wp_db_user: 'admin'
    wp_db_password: 'redhat1234'
    wp_db_host: 'localhost'
  pre_tasks:
    - name: get facts of web001
      setup
      register facts_web001
      delegate_to: web001

   - name: Show Facts
     debug:  
       var: facts_web001
  roles:
    - ansible-role-wordpress
