- name: Install Wordpress Application
  hosts: web001

- name: Wait for web001 to be completed
  hosts: web002
  become: yes
  become_method: sudo
  become_user: root
  tasks: 
    - name: Wait unitil web001 is ready
      wait_for:
        path: /tmp/web001
      delegate_to: ansible.rhlab.ch
      remote_user: azureadm

    - name: Install libsemanage-python
      yum: 
        name: libsemanage-python
        state: installed

#- name: Install MariaDB
#  hosts: web002
#  become: true
#  vars:
#    mariadb_bind_address: '0.0.0.0'
#    mariadb_root_password: '&othErEek97FrewlAyd?'
#    mariadb_databases:
#      - wordpress_db
#    mariadb_users:
#      - name: wordpress_usr
#        password: ywIapecJalg6
#        priv: wordpress_db.*:ALL
##        host: '192.168.56.%'
#  roles:
#    - bertvv.mariadb

- name: Install Wordpress Application
  hosts: web002
  become: true
  vars:
    httpd_scripting: 'php'

    wordpress_database_host: "{{ hostvars['web001'].ansible_local.custom.rhlabip.prvip }}"
    wordpress_database: wordpress_db
    wordpress_user: wordpress_usr
    wordpress_password: ywIapecJalg6
    wordpress_plugins:
      - name: wp-super-cache
        version: 1.4.5
      #- name: jetpack
      #  version: 3.7.2
      - name: lipsum
    #wordpress_themes:
      #- name: xcel
      #  version: 1.0.9
  roles:
    - bertvv.httpd
    - ansible-role-wordpress

